fun main(){
    print("Enter student Enrollment No. : ")
    var enr= readLine()
    print("Enter student Name : ")
    var name= readLine()
    print("Enter student Branch : ")
    var br= readLine()
    print("Enter student Class : ")
    var cl= readLine()
    print("Enter student Batch : ")
    var b= readLine()
    print("Enter student College Name : ")
    var cname= readLine()
    print("Enter student University Name : ")
    var uname= readLine()
    print("Enter student Age : ")
    var age= readLine()
    println("\n\n*********************************************\n\n")
    println("Student's Data")
    println("Enrollment No. : $enr")
    println("Name : $name")
    println("Branch : $br")
    println("Class : $cl")
    println("Batch : $b")
    println("College Name : $cname")
    println("University Name : $uname")
    println("Age : $age")
}